import './globals.css'
import type { Metadata } from 'next'
import { inter } from '@/styles/fonts'

export const metadata: Metadata = {
  title: 'rennie Blind',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
